# Generated by Django 4.0.1 on 2022-01-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_blog_delete_entregable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Page',
        ),
    ]
