# Generated by Django 4.0.1 on 2022-01-27 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_remove_page_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 1, 45, 12, 980034), editable=False),
        ),
    ]
