# Generated by Django 4.0.1 on 2022-01-29 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_alter_page_cuerpo_alter_page_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 29, 19, 26, 21, 414007)),
        ),
    ]
