# Generated by Django 4.0.1 on 2022-01-31 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_alter_page_fecha_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cuerpo',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 31, 19, 25, 37, 42660)),
        ),
    ]
