# Generated by Django 4.0.1 on 2022-02-02 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0017_alter_page_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 18, 10, 7, 155764)),
        ),
        migrations.AlterField(
            model_name='page',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ImagenesBlog'),
        ),
    ]
