# Generated by Django 4.0.1 on 2022-02-02 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0018_alter_page_fecha_alter_page_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 18, 55, 27, 180923)),
        ),
    ]
