# Generated by Django 4.0.1 on 2022-02-02 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0019_alter_page_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='imagen',
        ),
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 19, 20, 32, 16654)),
        ),
    ]
