# Generated by Django 4.0.1 on 2022-02-03 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0020_remove_page_imagen_alter_page_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='Default_Image.png', null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 2, 22, 4, 3, 795865)),
        ),
    ]
