# Generated by Django 4.0.1 on 2022-02-04 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0022_alter_avatar_imagen_alter_page_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='Default_Image.png', null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 21, 54, 6, 42737)),
        ),
    ]
