# Generated by Django 4.0.1 on 2022-02-06 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0023_alter_avatar_imagen_alter_page_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='avatares/Default_Image.png', null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 20, 16, 55, 82467)),
        ),
    ]
