# Generated by Django 4.0.1 on 2022-02-07 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0025_alter_avatar_imagen_alter_page_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 21, 14, 52, 779052)),
        ),
    ]
