# Generated by Django 4.0.1 on 2022-02-08 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0026_alter_page_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='blog_imagenes'),
        ),
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 7, 21, 2, 33, 51655)),
        ),
    ]
