# Generated by Django 4.0.1 on 2022-02-13 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0037_alter_page_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='page',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 5, 15, 26, 715154)),
        ),
    ]
